version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для веб-интерфейса RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:                                                                                                                                                                                                                                   
      - leonid_network
      
  postgres:
    image: postgres:16.1
    container_name: last_fight_postgres
    #restart: always
    environment:
      POSTGRES_DB: "main_database"
      POSTGRES_USER: "leonid"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - leonid_network
    
  orchestrator-server:
    build:
      context: .
      dockerfile: Orchestrator
    container_name: orchestrator_server
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8082:8082"
      - "5000:5000"
    networks:
      - leonid_network

  solver-server:
    build:
      context: .
      dockerfile: Solver
    container_name: solver_server
    depends_on:
      - orchestrator-server
      - postgres
      - rabbitmq
    networks:
      - leonid_network

  frontend-server:
    build:
      context: .
      dockerfile: Frontend
    container_name: frontend_server
    depends_on:
      - orchestrator-server
      - postgres
    ports:
      - "8081:8081"
    networks:
      - leonid_network

networks:
  leonid_network:
    driver: bridge