environment_mode: "dev" # Среда работы - на локальной машине, доступны ("local", "prodaction")
postgres:
  host: "last_fight_postgres" #"last_fight_postgres"
  port: "5432"
  user: "leonid"
  password: "password"
  dbname: "main_database"
rabbitmq:
  host: "rabbitmq"
  port: "5672"
  task_exchange: "task_exchange"
  result_exchange: "result_exchange"
  quantity_solvers: 1
http_server:
  address: ":8082" # Адрес сервера
  request_timeout: 4s # Таймаут запроса
  connection_timeout: 60s # Таймаут соединения
grpc_server:
  host: "orchestrator_server"
  port: "5000"